### ISSUE TITLE
`obs_richness_ts()` silently removes data?

### ISSUE THREAD

**Issue by wlangera** [b-cubed-eu/b3gbi#61]
If I calculate observed species richness, I get different results using **b3gbi** (v0.6.1) or the using the internal **dplyr** code of  `calc_ts.obs_richness()`.
When I debug  `calc_ts.obs_richness()`, I noticed that the dataset is much smaller than the initial input data: 2127 rows while the initial data was 3833 rows.

Even if there is a valid reason for this, there should be some kind of message or warning stating why we remove data in the process of indicator calculation.

``` r
# Load packages
library(b3gbi)
library(dplyr)

# Process cube
denmark_cube <- process_cube(
  system.file("extdata", "denmark_mammals_cube_eqdgc.csv", package="b3gbi"),
  first_year = 2020,
  last_year = 2021
)

# Calculate observed species richness with b3gbi
obs_richness_ts(denmark_cube, ci_type = "none")$data
#> # A tibble: 2 × 2
#>    year diversity_val
#>   <dbl>         <int>
#> 1  2020            62
#> 2  2021            61

# Calculate observed species richness with dplyr
x <-
  denmark_cube$data %>%
  dplyr::select(year, taxonKey) %>%
  dplyr::arrange(year)

x %>%
  dplyr::summarise(diversity_val = dplyr::n_distinct(taxonKey),
                   .by = "year")
#> # A tibble: 2 × 2
#>    year diversity_val
#>   <dbl>         <int>
#> 1  2020            70
#> 2  2021            69
```

<sup>Created on 2025-05-20 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by shawndove** [comment]
Hi Ward, thanks for reporting this. It turned out to be a problem in the way that quarter degree grid codes were being translated. I misunderstood the system used by GBIF to assign the codes, and so my translation function was working for the southern hemisphere but not for the northern hemisphere. So some of the occurrences were ending up outside the area of the cube and getting cut off. I will post a fix for this soon.

**Comment by shawndove** [comment]
Should be working in v0.6.3

**Comment by wlangera** [comment]
I still get a different result? Did you test my reprex?

``` r
# Load packages
library(b3gbi)
library(dplyr)

# Process cube
denmark_cube <- process_cube(
  system.file("extdata", "denmark_mammals_cube_eqdgc.csv", package="b3gbi"),
  first_year = 2020,
  last_year = 2021
)

# Calculate observed species richness with b3gbi
obs_richness_ts(denmark_cube, ci_type = "none")$data
#> # A tibble: 2 × 2
#>    year diversity_val
#>   <dbl>         <int>
#> 1  2020            63
#> 2  2021            61

# Calculate observed species richness with dplyr
x <-
  denmark_cube$data %>%
  dplyr::select(year, taxonKey) %>%
  dplyr::arrange(year)

x %>%
  dplyr::summarise(diversity_val = dplyr::n_distinct(taxonKey),
                   .by = "year")
#> # A tibble: 2 × 2
#>    year diversity_val
#>   <dbl>         <int>
#> 1  2020            70
#> 2  2021            69
```

<sup>Created on 2025-05-21 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by shawndove** [comment]
In fact, you've uncovered a larger issue in the package. I've been using rnaturalearth data but didn't include oceans. This is relatively straightforward to solve when you are calculating over the entire cube (as in your reprex), but more complicated for cases when the user wants specific area(s) from the cube, since GBIF uses economic zones and rnaturalearth does not. So it will take a bit longer to produce a proper fix for this. I'm working on it though.

**Comment by shawndove** [comment]
This is fixed now
